### List all menus
GET http://localhost:3000/menus

### Show a menu
GET http://localhost:3000/menus/1

### Create a menu
POST http://localhost:3000/menus
Content-Type: application/json

{
  "name": "Breakfest",
  "description": "Breakfest menu"
}

### Update a menu
PUT http://localhost:3000/menus/1
Content-Type: application/json

{
  "name": "Menu 1 updated",
  "description": "Menu 1 description updated"
}

### Delete a menu
DELETE http://localhost:3000/menus/1

### List all menu items
GET http://localhost:3000/menus/1/menu_items

### Show a menu item
GET http://localhost:3000/menus/1/menu_items/1